[versions]
jetbrains-annotations = "24.0.1"
loom = "1.6.+"
gson = "2.10.1"
# Testing
junit-jupiter = "5.10.0"
junit-launcher = "1.10.0"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
loom-fabric = { module = "net.fabricmc:fabric-loom", version.ref = "loom" }
loom-quilt = { module = "org.quiltmc:loom", version.ref = "loom" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
# Testing
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-launcher" }
